name: imdb-scrapp
channels:
  - defaults
dependencies:
  - pandas
  - requests
  - beautifulsoup4
  - python=3.9
  - autopep8
  - ipykernel
  - pandas-profiling
  - seaborn
  - statsmodels
  - scipy

